name: OkakAC
version: 1.0
# Указываем только имя класса, так как он лежит без пакета
main: Main
api-version: 1.16
softdepend: [ProtocolLib]
commands:
  ac:
    description: Включить/выключить античит
    usage: /ac <on/off>
  acabuch:
    description: Режим обучения алгоритма
    usage: /acabuch <cheat/necheat> <killaura> <ник> <on/off>
  freeze:
    description: Заморозить игрока на месте
    usage: /freeze <ник>